[profile.default]
src = "src"
out = "out"
optimizer = true
optimizer_runs = 999
libs = ["lib", "lib/v2-core", "lib/v2-periphery", "lib/uniswap-lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@uniswap/v2-core/=lib/v2-core/",
    "@uniswap/lib/=lib/uniswap-lib/",
    "v2-core/=lib/v2-core/contracts/",
    "v2-periphery/=lib/v2-periphery/contracts/",
    "uniswap-lib/=lib/uniswap-lib/contracts/"
]
auto_detect_solc = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options